#!/bin/bash
# Creates the Firestore indexes Dabber needs (from firestore.indexes.json).
# Run in Google Cloud Shell: bash dabber-indexes.sh <firebase-project-id>
set -u
P="${1:?usage: bash dabber-indexes.sh <firebase-project-id>}"
gcloud services enable firestore.googleapis.com --project="$P" >/dev/null 2>&1
echo "Creating composite indexes in project $P ..."
gcloud firestore indexes composite create --project="$P" --collection-group=conversations --query-scope=collection --field-config=field-path=uid,order=ascending --field-config=field-path=startedAt,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=conversations --query-scope=collection --field-config=field-path=uid,order=ascending --field-config=field-path=startedAt,order=ascending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=admin_audit --query-scope=collection --field-config=field-path=targetUid,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=admin_audit --query-scope=collection --field-config=field-path=action,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=admin_audit --query-scope=collection --field-config=field-path=adminEmail,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=payments --query-scope=collection --field-config=field-path=status,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=payments --query-scope=collection --field-config=field-path=kind,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=payments --query-scope=collection --field-config=field-path=kind,order=ascending --field-config=field-path=status,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=payments --query-scope=collection --field-config=field-path=kind,order=ascending --field-config=field-path=status,order=ascending --field-config=field-path=at,order=ascending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=email_log --query-scope=collection --field-config=field-path=to,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=email_log --query-scope=collection --field-config=field-path=result,order=ascending --field-config=field-path=at,order=ascending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=email_log --query-scope=collection --field-config=field-path=result,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=usage --query-scope=collection --field-config=field-path=key,order=ascending --field-config=field-path=count,order=ascending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=support_messages --query-scope=collection --field-config=field-path=status,order=ascending --field-config=field-path=at,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=groups --query-scope=collection --field-config=field-path=kind,order=ascending --field-config=field-path=createdAt,order=descending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=payments --query-scope=collection --field-config=field-path=uid,order=ascending --field-config=field-path=kind,order=ascending --field-config=field-path=status,order=ascending --async --quiet 2>&1 | grep -v -i 'already exists' || true
gcloud firestore indexes composite create --project="$P" --collection-group=progress --query-scope=collection-group --field-config=field-path=lessonId,order=ascending --field-config=field-path=status,order=ascending --async --quiet 2>&1 | grep -v -i 'already exists' || true
echo "Updating single-field indexes ..."
gcloud firestore indexes fields update lessonId --project="$P" --collection-group=progress --index=order=ascending,query-scope=collection --index=order=descending,query-scope=collection --index=array-config=contains,query-scope=collection --index=order=ascending,query-scope=collection-group --async --quiet || true
gcloud firestore indexes fields update status --project="$P" --collection-group=final_exam_attempts --index=order=ascending,query-scope=collection --index=order=descending,query-scope=collection --index=array-config=contains,query-scope=collection --index=order=ascending,query-scope=collection-group --async --quiet || true
gcloud firestore indexes fields update result.passed --project="$P" --collection-group=final_exam_attempts --index=order=ascending,query-scope=collection --index=order=descending,query-scope=collection --index=array-config=contains,query-scope=collection --index=order=ascending,query-scope=collection-group --async --quiet || true
gcloud firestore indexes fields update createdAt --project="$P" --collection-group=pack_enrollments --index=order=ascending,query-scope=collection --index=order=descending,query-scope=collection --index=array-config=contains,query-scope=collection --index=order=ascending,query-scope=collection-group --index=order=descending,query-scope=collection-group --async --quiet || true
echo; echo "Done. Indexes build in the background (a few minutes). Status:"
echo "https://console.firebase.google.com/project/$P/firestore/indexes"
